### PR TITLE
Fix not found request for forward response

### LINKED ISSUE #348: Fix unexpected max latency in output of `stat`
### RaftKeeper version
2.1.1
### Description
Got a large number of max latency
```
echo stat|nc localhost 2181
RaftKeeper version: RaftKeeper v2.1.1
Clients:
 127.0.0.1:11518(recved=0,sent=0)
 11.118.148.89:61362(recved=323087487,sent=325752485)
 11.118.149.166:26454(recved=835632782,sent=842340316)
 11.118.249.188:12130(recved=899254869,sent=906579323)
 11.115.152.197:22470(recved=890502441,sent=897937851)
 11.118.71.54:46136(recved=924492875,sent=931955872)
 11.118.135.8:53452(recved=943845776,sent=951538936)
 11.102.65.60:18428(recved=949945813,sent=957763382)
 11.102.64.186:31594(recved=1020374675,sent=1028727434)
 11.118.125.232:29714(recved=866264742,sent=873505846)
 11.102.65.67:22876(recved=1122690863,sent=1132029069)
 11.102.64.101:20116(recved=1250031662,sent=1260370136)
 11.134.48.159:27372(recved=892861462,sent=900254139)

Latency min/avg/max: 0/0/18446744073709551615
```
18446744073709551615 which is 0xffffffffffffff meaning -1 for int64

### LINKED ISSUE #350: Unexpected forwarding timeout when the system pressure is low
### RaftKeeper version
v2.1.1
### Description
image

follower1
```
2024.09.04 02:27:28.450203 [ 96 ] <Warning> RequestForwarder: Forward request #User#2031#1002562415 timeout
2024.09.04 02:27:28.450231 [ 96 ] <Warning> RequestProcessor: Found error request #0x7ef#1002562415#Remove accepted:false error_code:-2
2024.09.04 02:27:28.450286 [ 56 ] <Warning> RequestProcessor: Not found error request #0x7ef#1002562415#Remove accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
2024.09.04 02:51:29.757679 [ 104 ] <Warning> RequestForwarder: Forward request #User#2051#897306435 timeout
2024.09.04 02:51:29.757704 [ 104 ] <Warning> RequestProcessor: Found error request #0x803#897306435#Create accepted:false error_code:-2
2024.09.04 02:51:29.757760 [ 56 ] <Warning> RequestProcessor: Not found error request #0x803#897306435#Create accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
2024.09.04 04:10:48.371145 [ 93 ] <Warning> RequestForwarder: Forward request #User#2058#791636908 timeout
2024.09.04 04:10:48.371193 [ 93 ] <Warning> RequestProcessor: Found error request #0x80a#791636908#Multi accepted:false error_code:-2
2024.09.04 04:10:48.371310 [ 56 ] <Warning> RequestProcessor: Not found error request #0x80a#791636908#Multi accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
2024.09.04 04:45:57.943673 [ 93 ] <Warning> RequestForwarder: Forward request #User#2058#793238364 timeout
2024.09.04 04:45:57.943708 [ 93 ] <Warning> RequestProcessor: Found error request #0x80a#793238364#Multi accepted:false error_code:-2
2024.09.04 04:45:57.943768 [ 56 ] <Warning> RequestProcessor: Not found error request #0x80a#793238364#Multi accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
2024.09.04 06:45:48.927674 [ 96 ] <Warning> RequestForwarder: Forward request #User#2047#907929485 timeout
2024.09.04 06:45:48.927703 [ 96 ] <Warning> RequestProcessor: Found error request #0x7ff#907929485#Multi accepted:false error_code:-2
2024.09.04 06:45:48.927766 [ 56 ] <Warning> RequestProcessor: Not found error request #0x7ff#907929485#Multi accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
2024.09.04 07:05:16.180588 [ 99 ] <Warning> RequestForwarder: Forward request #User#2038#968536106 timeout
2024.09.04 07:05:16.180622 [ 99 ] <Warning> RequestProcessor: Found error request #0x7f6#968536106#Multi accepted:false error_code:-2
2024.09.04 07:05:16.180691 [ 56 ] <Warning> RequestProcessor: Not found error request #0x7f6#968536106#Multi accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
2024.09.04 08:22:58.275716 [ 93 ] <Warning> RequestForwarder: Forward request #User#2058#803805465 timeout
2024.09.04 08:22:58.275746 [ 93 ] <Warning> RequestProcessor: Found error request #0x80a#803805465#Multi accepted:false error_code:-2
2024.09.04 08:22:58.275798 [ 56 ] <Warning> RequestProcessor: Not found error request #0x80a#803805465#Multi accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
```
follower2
```
2024.09.03 21:38:21.128696 [ 96 ] <Warning> RequestForwarder: Forward request #User#2053#868134746 timeout
2024.09.03 21:38:21.128728 [ 96 ] <Warning> RequestProcessor: Found error request #0x805#868134746#Multi accepted:false error_code:-2
2024.09.03 21:38:21.128791 [ 54 ] <Warning> RequestProcessor: Not found error request #0x805#868134746#Multi accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
2024.09.03 22:50:45.386748 [ 96 ] <Warning> RequestForwarder: Forward request #User#2053#871263725 timeout
2024.09.03 22:50:45.386782 [ 96 ] <Warning> RequestProcessor: Found error request #0x805#871263725#Multi accepted:false error_code:-2
2024.09.03 22:50:45.386840 [ 54 ] <Warning> RequestProcessor: Not found error request #0x805#871263725#Multi accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
2024.09.04 00:04:29.677325 [ 92 ] <Warning> RequestForwarder: Forward request #User#2049#901054523 timeout
2024.09.04 00:04:29.677352 [ 92 ] <Warning> RequestProcessor: Found error request #0x801#901054523#Multi accepted:false error_code:-2
2024.09.04 00:04:29.677411 [ 54 ] <Warning> RequestProcessor: Not found error request #0x801#901054523#Multi accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
2024.09.04 00:34:07.876210 [ 95 ] <Warning> RequestForwarder: Forward request #User#2036#959245176 timeout
2024.09.04 00:34:07.876239 [ 95 ] <Warning> RequestProcessor: Found error request #0x7f4#959245176#Multi accepted:false error_code:-2
2024.09.04 00:34:07.876292 [ 54 ] <Warning> RequestProcessor: Not found error request #0x7f4#959245176#Multi accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
2024.09.04 08:54:16.162751 [ 100 ] <Warning> RequestForwarder: Forward request #User#2025#1053668331 timeout
2024.09.04 08:54:16.162780 [ 100 ] <Warning> RequestProcessor: Found error request #0x7e9#1053668331#Multi accepted:false error_code:-2
2024.09.04 08:54:16.162831 [ 54 ] <Warning> RequestProcessor: Not found error request #0x7e9#1053668331#Multi accepted:false error_code:-2 in pending queue. Possible reason: 1. request forwarding error; 2.close requests from deadSessionCleanThread are not put into pending queue; 3.error occurs(forward or append entries) but request is still committed, 'processCommittedRequest' may delete request from pending request first, so here we can not find it. We also delete it from errors.
```

### PR DESCRIPTION
**Pull request by lzydmxy**
### Which issues of this PR fixes:

This PR try to fix #350, fix #348

### Change log:

- Move request to `forward_request_queue` before forward request to leader
- Use `pending_request-> create_time`(self's steady_clock) instead of `committed_request-> create_time` (leader's steady_clock) to calculate request time cost
- Standardized `forward request`, `forward response` printing in logs

### CODE REVIEW

File: src/Service/RequestForwarder.cpp [hunk 1]
```diff
@@ -260,10 +261,18 @@ bool RequestForwarder::removeFromQueue(RunnerId runner_id, ForwardResponsePtr fo
 
 void RequestForwarder::processResponse(RunnerId runner_id, ForwardResponsePtr forward_response_ptr)
 {
-    bool found = removeFromQueue(runner_id, forward_response_ptr);
+    if (!removeFromQueue(runner_id, forward_response_ptr))
+    {
+        LOG_WARNING(log, "Not found request in runner {} for forward response {}, current request_queue size {}, detail {}",
```
Comment (JackyWoo) [inline src/Service/RequestForwarder.cpp:266]: Lack of a parameter in log pattern

File: src/Service/RequestProcessor.cpp [hunk 2]
```diff
@@ -160,35 +160,34 @@ bool RequestProcessor::shouldProcessCommittedRequest(const RequestForSession & c
     if (first_pending_request.request->xid == committed_request.request->xid)
     {
         found_in_pending_queue = true;
+        committed_request.create_time = first_pending_request.create_time;
```
Comment (JackyWoo) [inline src/Service/RequestProcessor.cpp:163]: Why reset the time?

**Comment by JackyWoo** [comment]
There is a little issue in CI that the failed test report does not squash test cases with different sanatize types.

File: src/Service/KeeperCommon.h [hunk 3]
```diff
@@ -37,9 +37,12 @@ struct RequestForSession
     int64_t session_id;
     Coordination::ZooKeeperRequestPtr request;
 
-    /// measured in millisecond
+    /// When request create, millisecond count since system start up, used for calculate request duration
     int64_t create_time{};
 
+    /// When leader append write request, millisecond count since 1970-1-1, used for node stat ctime and mtime.
+    int64_t process_time{};
```
Comment (JackyWoo) [inline src/Service/KeeperCommon.h:44]: Why we need the `process_time `?

File: src/Service/KeeperCommon.h [hunk 4]
```diff
@@ -37,9 +37,12 @@ struct RequestForSession
     int64_t session_id;
     Coordination::ZooKeeperRequestPtr request;
 
-    /// measured in millisecond
+    /// When request create, millisecond count since system start up, used for calculate request duration
     int64_t create_time{};
```
Comment (JackyWoo) [inline src/Service/KeeperCommon.h:41]: `create_time` is generated by `return duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now().time_since_epoch()).count();` which is also the millisecond count since 1970-1-1.

File: src/Service/KeeperCommon.h (hunk 3 above)
Comment (lzydmxy) [reply src/Service/KeeperCommon.h:44]: std::chrono::steady_clock is a relative clock used for measuring time intervals. We cannot use it for a node's ctime and mtime. We need an additional std::chrono::system_clock to store the modification and creation times of a node.

File: src/Service/KeeperCommon.h (hunk 4 above)
Comment (lzydmxy) [reply src/Service/KeeperCommon.h:41]: std::chrono::steady_clock::now().time_since_epoch().count() values can indeed differ significantly between different nodes or machines. This is because steady_clock's epoch is not tied to a specific point in real-world time and is typically initialized at the start of the system or process.

File: src/Service/ForwardConnection.cpp [hunk 5]
```diff
@@ -24,7 +24,7 @@ void ForwardConnection::connect()
     {
         try
         {
-            LOG_TRACE(log, "Try connect forward server {}", endpoint);
+            LOG_INFO(log, "Try connect forward server {}", endpoint);
```
[the remark this answers is not in the document]
Comment (lzydmxy) [reply src/Service/ForwardConnection.cpp:27]: > We'd better following the rule: log befor an action use xxxing and xxxed for after.

Ok, I will pay attention to tense issues in logs.

File: src/Service/RequestProcessor.cpp (hunk 2 above)
Comment (lzydmxy) [reply src/Service/RequestProcessor.cpp:163]: `committed_request.create_time` is leader's `steady_clock` for this requests, we should set it to local `steady_clock` for request to calculate request duration.

File: src/Service/KeeperCommon.h (hunk 3 above)
Comment (JackyWoo) [reply src/Service/KeeperCommon.h:44]: Set`create_time` to system clock?

Comment (lzydmxy) [reply src/Service/KeeperCommon.h:44]: > Set create_time to system clock?

`create_time` is when node see this user request and create it as session request
`process_time` is when RequestAccumulator sees this session request and tries to commit it. 
We assign the leader's system_clock as `process_time` to every request before `raft_instance->append_entries()` to ensure the sequential order of `process_time`, meaning the `process_tim`e of an earlier processed request should be less than that of a later one. This ensures the relative accuracy of a node's `ctime` and `mtime`. Due to the pipeline and forwarding processes, there might be cases where the `create_time` of an earlier processed request is greater than a later one, causing confusion in the node's `ctime` and `mtime`. `create_time` and `process_time` should be distinct: one is relative, used to measure request duration, and the other is absolute, used to record the historical operation time of the node."

Comment (lzydmxy) [reply src/Service/KeeperCommon.h:44]: @JackyWoo Please review when you have time.

Comment (JackyWoo) [reply src/Service/KeeperCommon.h:44]: Sure, but there might be some delay.

**Review by JackyWoo — APPROVED** [review]
