### PR TITLE
Fix already registered after forward expiration

### LINKED ISSUE #117: Test `test_forward_expiration` is flaky
### RaftKeeper version
2.0.2
### Description
Related #107 
```
<Fatal> : Logical error: 'Server 2 client 5 already registered in dispatcher'.
2023-12-05T07:19:47.5016221Z 2023.12.05 07:08:41.564703 [ 11 ] <Trace> BaseDaemon: Received signal 6
2023-12-05T07:19:47.5016532Z 2023.12.05 07:08:41.565023 [ 130 ] <Fatal> BaseDaemon: ########################################
2023-12-05T07:19:47.5017099Z 2023.12.05 07:08:41.565059 [ 130 ] <Fatal> BaseDaemon: (version v2.0.3, build id: B913DEBD2CA7B999) (from thread 128) Received signal Aborted (6)
2023-12-05T07:19:47.5017346Z 2023.12.05 07:08:41.565097 [ 130 ] <Fatal> BaseDaemon: 
2023-12-05T07:19:47.5018332Z 2023.12.05 07:08:41.565156 [ 130 ] <Fatal> BaseDaemon: Stack trace: 0x7f46a9617a7c 0x7f46a95c3476 0x7f46a95a97f3 0x95f166 0x95f719 0xb94557 0xb875f2 0xb27fb8 0xb1f9dc 0xb2d8c3 0x13c9570 0xa92436 0xa85a4a 0xa806e7 0x1468ee9 0x7f46a9615b43 0x7f46a96a6bb4
```

### PR DESCRIPTION
**Pull request by lzydmxy**
…der one, and add new one

### Which issues of this PR fixes:

This PR try to fix #117 #107

### Change log:

Don't throw exception when client already registered, just release older one, and add new one

### CODE REVIEW

File: src/Service/KeeperDispatcher.cpp [hunk 1]
```diff
@@ -336,9 +336,17 @@ void KeeperDispatcher::registerSession(int64_t session_id, ZooKeeperResponseCall
 void KeeperDispatcher::registerForward(ForwardingClientId client_id, ForwardResponseCallback callback)
 {
     std::lock_guard lock(forward_to_response_callback_mutex);
-    if (!forward_to_response_callback.try_emplace(client_id, callback).second)
-        throw Exception(
-            RK::ErrorCodes::LOGICAL_ERROR, "Server {} client {} already registered in dispatcher", client_id.first, client_id.second);
+
+    if (forward_to_response_callback.contains(client_id))
+    {
+        LOG_INFO(log, "Get server_id {}, client_id {} new registered, will destroy older one", client_id.first, client_id.second);
```
Comment (JackyWoo) [inline src/Service/KeeperDispatcher.cpp:342]: info -> warn

Comment (JackyWoo) [reply src/Service/KeeperDispatcher.cpp:342]: log message -> "Receive new forwarding connection from {}/{}, will destroy the older one"

File: src/Service/KeeperDispatcher.cpp [hunk 2]
```diff
@@ -336,9 +336,17 @@ void KeeperDispatcher::registerSession(int64_t session_id, ZooKeeperResponseCall
...
+        auto call_back = forward_to_response_callback[client_id];
```
Comment (JackyWoo) [inline src/Service/KeeperDispatcher.cpp:343]: auto -> auto &

Comment (JackyWoo) [inline src/Service/KeeperDispatcher.cpp:343]: auto -> "auto &"

Comment (JackyWoo) [inline src/Service/KeeperDispatcher.cpp:343]: auto -> "auto &"

File: src/Service/KeeperDispatcher.cpp [hunk 3]
```diff
@@ -336,9 +336,17 @@ void KeeperDispatcher::registerSession(int64_t session_id, ZooKeeperResponseCall
...
+        forward_to_response_callback.erase(client_id);
```
Comment (JackyWoo) [inline src/Service/KeeperDispatcher.cpp:344]: erase after call_back invoked

Comment (JackyWoo) [inline src/Service/KeeperDispatcher.cpp:344]: erase after call_back invoked

File: src/Service/ForwardingConnectionHandler.cpp [hunk 4]
```diff
@@ -348,6 +348,12 @@ void ForwardingConnectionHandler::onSocketError(const AutoPtr<ErrorNotification>
 
 void ForwardingConnectionHandler::sendResponse(ForwardResponsePtr response)
 {
+    if (response->forwardType() == ForwardType::Destroy)
+    {
+        delete this;
```
Comment (JackyWoo) [inline src/Service/ForwardingConnectionHandler.cpp:353]: I think delete should occur on the IO thread to avoid unexpected behavior, so you should invoke the delete in `onSocketWritable` method.

File: src/Service/ForwardResponse.h [hunk 5]
```diff
@@ -21,6 +21,7 @@ enum ForwardType : int8_t
     GetSession = 3, /// get session id
     UpdateSession = 4, /// session reconnect
     Operation = 5, /// all write requests after the connection is established
+    Destroy = 6,
```
Comment (JackyWoo) [inline src/Service/ForwardResponse.h:24]: Add a comment. "Only used in server side to indicate that the connection is stale and server should close it."

File: src/Service/KeeperDispatcher.cpp (hunk 2 above)
Comment (lzydmxy) [reply src/Service/KeeperDispatcher.cpp]: It's cheap to copy call_back (it just an std::function object).

File: src/Service/ForwardingConnectionHandler.h [hunk 6]
```diff
@@ -90,6 +90,9 @@ class ForwardingConnectionHandler
     void processHandshake();
     void processRaftRequest(ForwardRequestPtr request);
     void processSessions(ForwardRequestPtr request);
+
+    // mark is stop by dispatcher
+    bool is_destroy;
```
Comment (JackyWoo) [inline src/Service/ForwardingConnectionHandler.h:95]: is_destroy -> need_destroy

File: src/Service/ForwardingConnectionHandler.h [hunk 7]
```diff
@@ -90,6 +90,9 @@ class ForwardingConnectionHandler
     void processHandshake();
     void processRaftRequest(ForwardRequestPtr request);
     void processSessions(ForwardRequestPtr request);
+
+    // mark is stop by dispatcher
```
Comment (JackyWoo) [inline src/Service/ForwardingConnectionHandler.h:94]: "The connection is stale and need destroyed"
