### PR TITLE
Organize the integration tests log output

### LINKED ISSUE #11: Organize the integration tests log output
**Description**
Now integration tests log output is messy. We'd better do some optimization. 

1. We can leverage the python logging component and setup log level carfully.
2. We should print raftkeeper instances log if a test failed.

### PR DESCRIPTION
**Pull request by JackyWoo**
This PR will close #11 

### change log:

1. organize the integration tests log output.
2. fix code style of integration tests.
3. optimize `run-integration-tests.sh`
4. fix some test cases
5. Add timeout to nuraft auto forward

### CODE REVIEW

File: src/Service/KeeperDispatcher.cpp [hunk 1]
```diff
@@ -61,7 +61,7 @@ void KeeperDispatcher::requestThreadFakeZk(size_t thread_index)
                         request_for_session.request->getOpNum());
                     request_processor->push(request_for_session);
                 }
-                else if (!request_for_session.isForwardRequest())
+                else if (!request_for_session.isForwardRequest() && request_for_session.request->getOpNum() != Coordination::OpNum::Close)
```
Comment (nicelulu) [inline src/Service/KeeperDispatcher.cpp:64]: Why need ```&& request_for_session.request->getOpNum() != Coordination::OpNum::Close``` ?

Comment (JackyWoo) [reply src/Service/KeeperDispatcher.cpp:64]: In case of network partition,  separated leader will print illegal log.

Comment (nicelulu) [reply src/Service/KeeperDispatcher.cpp:64]: From ```sessionCleanerTask``` requests ? It is recommended to write in the comment that these close requests come from sessionCleanerTask.
