### PR TITLE
Don't send watch reponse if we got error in muiti writes ops

### LINKED ISSUE #326: Shouldn't process watch for MultiWrites when it got failed
### RaftKeeper version
2.0.4
### Description
```
zk.create("/test")
zk.exists("/test", watch=exists_watch)

transaction = zk.transaction()
transaction.create("/test")

transaction.commit()
```
The transaction got failed, but we still got  WatchedEvent(type='CREATED', state='CONNECTED', path='/test') from RaftKeeper

### PR DESCRIPTION
**Pull request by lzydmxy**
### Which issues of this PR fixes:

This PR try to fix #326

### CODE REVIEW

File: src/Service/KeeperStore.cpp [hunk 1]
```diff
@@ -1,3 +1,4 @@
+#include "Service/LoggerWrapper.h"
```
Comment (JackyWoo) [inline src/Service/KeeperStore.cpp:1]: use <>

File: src/Service/KeeperStore.cpp [hunk 2]
```diff
@@ -1365,15 +1366,20 @@ void KeeperStore::processRequest(
             {
                 if (zk_request->getOpNum() == Coordination::OpNum::Multi)
                 {
-                    auto * multi_request = dynamic_cast<Coordination::ZooKeeperMultiRequest *>(zk_request.get());
-                    for (auto & concrete_request : multi_request->requests)
+                    auto multi_response = std::dynamic_pointer_cast<Coordination::ZooKeeperMultiWriteResponse>(response);
+                    /// trigger watches for all requests
```
Comment (JackyWoo) [inline src/Service/KeeperStore.cpp:1370]: Add a comment "Last response is ok means the multi-request success."

**Comment by JackyWoo** [comment]
LGTM, except some little code style issues.

**Review by JackyWoo — APPROVED** [review]
