### PR TITLE
Fix request hunging in some case

### LINKED ISSUE #133: Fix request hunging in some case
### RaftKeeper version
v2.0.3
### Description
Fix request hunging in some case

### PR DESCRIPTION
**Pull request by JackyWoo**
### Which issues of this PR fixes:

This PR try to fix #133 

### Change log:

- No waiting if pending queue is not empty in request processor.

### CODE REVIEW

**Comment by JackyWoo** [comment]
@lzydmxy Please review the PR.

File: src/Service/RequestProcessor.cpp [hunk 1]
```diff
@@ -32,7 +32,21 @@ void RequestProcessor::run()
...
+                /// We should not wait when pending queue is not empty, for function 'moveRequestToPendingQueue'
+                /// moves all pending requests to pending queue.
+                /// Suppose there is a sequence of write-read requests, 'moveRequestToPendingQueue' move all requests
+                /// to pending queue and then the first loop handle the write request, then If we do not check the
+                /// pending queue in our wait condition, it will result in meaningless waiting.
+                size_t pending_requests_size{};
+                for (const auto & [_, runner_pending_requests] : pending_requests)
+                {
+                    for (const auto & [session_, session_pending_requests] : runner_pending_requests)
+                        pending_requests_size += session_pending_requests.size();
```
Comment (lzydmxy) [inline src/Service/RequestProcessor.cpp:46]: it seems better return false if not session_pending_requests.empty().

**Comment by lzydmxy** [comment]
LGTM
